# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.10

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/AliyunContainerService/log-pilot
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false

    # specify any bash command here prefixed with `run: `
    - run:
        name: static check
        command: |
          make misspell
          make static-check
          make vet
    - run:
        name: unit test
        command: |
          make test
    - run:
        name: build image
        command: |
          make container
    - run:
        name: codecov
        command: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)